### ISSUE TITLE
Add user friendly messages for Ruby Exceptions in YAML

### ISSUE THREAD

**Issue by mandysGit** [aumi9292/blogger#1]
- Blogger's intended users are new programmers
- Some of Ruby's Error messages can be difficult for a beginner to understand
- The task here is to add meaningful and user-friendly messages that are logged alongside the title of the Ruby Exceptions
- This will provide better understanding when a Ruby Exception is raised

**Comment by Leena** [comment]
Closing issue, everything well executed by @mandysGit via PR: https://github.com/aumi9292/blogger/pull/3
