### ISSUE TITLE
📝 Add Description to repo

### ISSUE THREAD

**Issue by Leena** [aumi9292/blogger#8]
Hey Austin! 
Could you fill this out please ? I didn't find a way to do it. Perhaps because you're the owner of the repo.
![image](https://user-images.githubusercontent.com/43962911/107150074-05190200-692a-11eb-9318-513a58ccbebc.png)

**Ideas**: 

1. Description: A command line developer tool to track exceptions.
2. And a hyperlink to https://rubygems.org/gems/ruby_blogger 
3. Say it's a ruby gem.
4. Anything else you deem important 😄

**Comment by aumi9292** [comment]
Perfect! I updated it, it should be good to go!
